# Generated by Django 3.2.4 on 2021-07-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_PRODUCTOS', '0005_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
